research_task:
  description: >
    Conduct thorough research on {topic}. Prioritize reputable, recent sources and extract actionable insights (facts, entities, links, examples).
  expected_output: >
    8 to 12 concise bullet points with sources/links (when available) summarizing the most relevant findings about {topic}.
  agent: researcher

author_agents_yaml_task:
  description: >
    Using the research context, produce a single valid YAML document or a CrewAI project about {topic}. Include at least the following agent entries (edit their wording to fit {topic}): researcher, writer, reviewer. For each, provide role, goal, backstory, and any minimal flags
    (e.g., verbose, allow_delegation). Output YAML only (no backticks, no prose).
  expected_output: >
    A single valid YAML document defining CrewAI agents tailored to {topic}.
    Example output for `agents.yaml`:
    researcher:
      role: <string>
      goal: <string>
      backstory: <string>
    writer:
      role: <string>
      goal: <string>
      backstory: <string>
    reviewer:
      role: <string>
      goal: <string>
      backstory: <string>
  agent: agents_prompt_engineer
  context:
    - research_task
  #output_file: outputs/test_agents.yaml
  #create_directory: true

author_tasks_yaml_task:
  description: >
    Using the research context, produce a single valid YAML document for a CrewAI project about {topic}. Define at least: research_task, write_task, review_task (or better names relevant to {topic}). For each task, include description, expected_output, and agent. Add dependencies using `context` where appropriate (e.g., formatting/synthesis tasks depend on research). Output YAML only (no backticks, no prose).
  expected_output: >
    A single valid YAML document defining CrewAI tasks mapped to the agents and referencing dependencies via `context`.
    Example output for `tasks.yaml`:
    research_task:
      description: <string>
      expected_output: <string>
      agent: <agent_name>
    write_task:
      description: <string>
      expected_output: <string>
      agent: <agent_name>
      context:
        - research_task
    review_task:
      description: <string>
      expected_output: <string>
      agent: <agent_name>
      context:
        - write_task
        - research_task
  agent: tasks_prompt_engineer
  context:
    - research_task
    - author_agents_yaml_task
  #output_file: outputs/test_tasks.yaml
  #create_directory: true
